<!DOCTYPE html>
<?php
require_once "../Dados/Conexao.php";
session_start();

$idtroca = $_POST["codigosolicitacao"];

$query2 = mysql_query("SELECT TROCA.*, (LIVRO_SOLICITADO.N_COD_USUARIO_IE) AS IDSOLICITADO, (LIVRO_SOLICITANTE.N_COD_USUARIO_IE) AS IDSOLICITANTE, USUARIO_SOLICITANTE.V_NOME FROM TROCA INNER JOIN LIVRO AS LIVRO_SOLICITADO ON LIVRO_SOLICITADO.N_COD_LIVRO = TROCA.N_COD_LIVRO INNER JOIN LIVRO AS LIVRO_SOLICITANTE ON LIVRO_SOLICITANTE.N_COD_LIVRO = TROCA.N_COD_LIVRO_SOLICITANTE INNER JOIN USUARIO AS USUARIO_SOLICITADO ON USUARIO_SOLICITADO.N_COD_USUARIO = LIVRO_SOLICITADO.N_COD_USUARIO_IE INNER JOIN USUARIO AS USUARIO_SOLICITANTE ON USUARIO_SOLICITANTE.N_COD_USUARIO = LIVRO_SOLICITANTE.N_COD_USUARIO_IE WHERE TROCA.N_COD_TROCA = '$idtroca'");

$coluna = mysql_fetch_array($query2);

$NOME = $coluna["V_NOME"];
$_SESSION["id_troca"] = $idtroca;
$_SESSION["id_solicitado"] = $coluna['IDSOLICITADO'];
$_SESSION["id_solicitante"] = $coluna['IDSOLICITANTE'];

if(isset($_GET['Ver']) == 'Aceitar')
{

  $query = mysql_query("UPDATE troca SET V_STATUS = 'ACEITO' where  N_COD_TROCA = $idtroca");
  if($query)
  {
	header("Location: ../Views/View_ChatTroca.php");
  }

}
?>